module.exports = {
    FETCH_TASK_BY_ID_RESPONSE: 'FETCH_TASK_BY_ID_RESPONSE',
    UPDATE_DATE_TIME_RESPONSE: 'UPDATE_DATE_TIME_RESPONSE',
    FETCH_TAG_BY_ID_RESPONSE: 'FETCH_TAG_BY_ID_RESPONSE',
    UPDATE_TAG_BY_ID_RESPONSE: 'UPDATE_TAG_BY_ID_RESPONSE',
};