module.exports = {
    FETCH_TASK_BY_ID_RESPONSE: 'FETCH_TASK_BY_ID_RESPONSE',
    FETCH_ALL_TASKS_RESPONSE: 'FETCH_ALL_TASKS_RESPONSE',
    FETCH_ALL_TASKS_RESPONSE_ERROR: 'FETCH_ALL_TASKS_RESPONSE_ERROR',
    UPDATE_DATE_TIME_RESPONSE: 'UPDATE_DATE_TIME_RESPONSE',
    FETCH_TAG_BY_ID_RESPONSE: 'FETCH_TAG_BY_ID_RESPONSE',
    UPDATE_TAG_BY_ID_RESPONSE: 'UPDATE_TAG_BY_ID_RESPONSE',
    PUT_TAG_RESPONSE: 'PUT_TAG_RESPONSE',
    POST_TAG_RESPONSE: 'POST_TAG_RESPONSE',
};