// fetchTaskById
export const FETCH_TASK_BY_ID = 'FETCH_TASK_BY_ID';
export const FETCH_TASK_BY_ID_RESPONSE = 'FETCH_TASK_BY_ID_RESPONSE';

// putTaskById
export const PUT_TASK_BY_ID = 'PUT_TASK_BY_ID';
export const PUT_TASK_BY_ID_RESPONSE = 'PUT_TASK_BY_ID_RESPONSE';

// fetchAllTags
export const FETCH_ALL_TAGS = 'FETCH_ALL_TAGS';
export const FETCB_ALL_TAGS_RESPONSE = 'FETCB_ALL_TAGS_RESPONSE'; 

// dateTimes
export const UPDATE_DATE_TIME = 'UPDATE_DATE_TIME';
export const UPDATE_DATE_TIME_RESPONSE = 'UPDATE_DATE_TIME_RESPONSE';
